export type Method = {
  id: string;
  name: string;
  nameEn: string;
  group: "Experimentação" | "Inferência e modelagem" | "Otimização e inteligência quantitativa" | "PLN e automação";
  groupEn: "Experimentation" | "Inference & Modeling" | "Optimization & Quant Intelligence" | "NLP & Automation";
  summary: string;
  summaryEn: string;
  relatedProjectIds: string[];
};

export const methods: Method[] = [
  // Experimentação
  {
    id: "ab-testing",
    name: "Testes A/B",
    nameEn: "A/B Testing",
    group: "Experimentação",
    groupEn: "Experimentation",
    summary: "Comparação de versões para validar melhorias e apoiar decisões comerciais com rigor analítico.",
    summaryEn: "Comparison of versions to validate improvements and support business decisions with analytical rigor.",
    relatedProjectIds: ["bayesian-promotions"]
  },
  {
    id: "multivariate-testing",
    name: "Testes multivariados",
    nameEn: "Multivariate Testing",
    group: "Experimentação",
    groupEn: "Experimentation",
    summary: "Estudo de interações entre múltiplos fatores ou variáveis em simultâneo.",
    summaryEn: "Study of interactions between multiple factors or variables simultaneously.",
    relatedProjectIds: ["bayesian-promotions"]
  },
  {
    id: "experimental-design",
    name: "Desenho experimental",
    nameEn: "Experimental Design",
    group: "Experimentação",
    groupEn: "Experimentation",
    summary: "Planeamento de testes com controlo de viéses, definição de amostras e seleção de métricas primárias/secundárias.",
    summaryEn: "Planning tests with bias control, sample size definitions, and selection of primary/secondary metrics.",
    relatedProjectIds: ["bayesian-promotions"]
  },
  {
    id: "power-analysis",
    name: "Análise de poder",
    nameEn: "Power Analysis",
    group: "Experimentação",
    groupEn: "Experimentation",
    summary: "Dimensionamento do tamanho amostral mínimo e sensibilidade para assegurar testes conclusivos.",
    summaryEn: "Determining the minimum sample size and sensitivity to ensure conclusive testing.",
    relatedProjectIds: ["bayesian-promotions"]
  },

  // Inferência e modelagem
  {
    id: "causal-inference",
    name: "Inferência causal",
    nameEn: "Causal Inference",
    group: "Inferência e modelagem",
    groupEn: "Inference & Modeling",
    summary: "Isolamento estatístico do efeito real de intervenções face a fatores externos ou sazonais.",
    summaryEn: "Statistical isolation of the real effect of interventions against external or seasonal factors.",
    relatedProjectIds: ["bayesian-promotions", "time-series-impact"]
  },
  {
    id: "uplift",
    name: "Modelagem de incrementalidade",
    nameEn: "Uplift Modeling",
    group: "Inferência e modelagem",
    groupEn: "Inference & Modeling",
    summary: "Estimativa do impacto incremental real gerado por uma promoção ou ação direta.",
    summaryEn: "Estimation of the real incremental impact (Uplift) generated by a promotion or direct action.",
    relatedProjectIds: ["time-series-impact", "segmentation-churn-ltv-roi"]
  },
  {
    id: "time-series",
    name: "Séries temporais",
    nameEn: "Time Series",
    group: "Inferência e modelagem",
    groupEn: "Inference & Modeling",
    summary: "Modelagem estatística de séries temporais para identificar padrões sazonais e tendências.",
    summaryEn: "Statistical modeling of time series to identify seasonal patterns and trends.",
    relatedProjectIds: ["time-series-impact"]
  },
  {
    id: "forecasting",
    name: "Previsão",
    nameEn: "Forecasting",
    summary: "Projeção de cenários futuros utilizando tendências históricas e limites de incerteza claros.",
    summaryEn: "Projection of future scenarios using historical trends and clear uncertainty boundaries.",
    group: "Inferência e modelagem",
    groupEn: "Inference & Modeling",
    relatedProjectIds: ["time-series-impact"]
  },
  {
    id: "survival-analysis",
    name: "Análise de sobrevivência",
    nameEn: "Survival Analysis",
    group: "Inferência e modelagem",
    groupEn: "Inference & Modeling",
    summary: "Modelagem probabilística do tempo decorrido até um determinado evento (ex: cancelamento ou falha).",
    summaryEn: "Probability modeling of time elapsed until a certain event (e.g., churn or failure).",
    relatedProjectIds: ["survival-time-to-event"]
  },

  // Otimização e inteligência quantitativa
  {
    id: "price-elasticity",
    name: "Elasticidade de preço",
    nameEn: "Price Elasticity",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Estimativa da variação da procura perante variações de preço para maximizar a receita.",
    summaryEn: "Estimation of demand variation due to price changes to maximize revenue.",
    relatedProjectIds: ["portfolio-pricing"]
  },
  {
    id: "maxdiff",
    name: "MaxDiff",
    nameEn: "MaxDiff",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Metodologia de melhor-pior escala para quantificar e priorizar preferências de utilizadores.",
    summaryEn: "Best-worst scaling methodology to quantify and prioritize user preferences.",
    relatedProjectIds: ["portfolio-pricing"]
  },
  {
    id: "conjoint",
    name: "Análise conjunta",
    nameEn: "Conjoint Analysis",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Análise baseada em escolhas discretas para avaliar o valor percebido de características de produto.",
    summaryEn: "Discrete choice analysis to evaluate the perceived value of product attributes.",
    relatedProjectIds: ["portfolio-pricing"]
  },
  {
    id: "turf",
    name: "Análise TURF",
    nameEn: "TURF Analysis",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Total Unduplicated Reach and Frequency. Otimização de portfólios de oferta para maximizar alcance líquido.",
    summaryEn: "Total Unduplicated Reach and Frequency. Optimizing offer portfolios to maximize net reach.",
    relatedProjectIds: ["portfolio-pricing"]
  },
  {
    id: "clustering",
    name: "Análise de agrupamento",
    nameEn: "Clustering",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Algoritmos não supervisionados para segmentação de clientes por comportamentos semelhantes.",
    summaryEn: "Unsupervised algorithms for segmenting customers by similar behaviors.",
    relatedProjectIds: ["segmentation-churn-ltv-roi"]
  },
  {
    id: "rfm-segmentation",
    name: "Segmentação RFM",
    nameEn: "RFM Segmentation",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Classificação de clientes com base em Recência, Frequência e Valor Monetário das transações.",
    summaryEn: "Client classification based on Recency, Frequency, and Monetary value of transactions.",
    relatedProjectIds: ["segmentation-churn-ltv-roi"]
  },
  {
    id: "churn",
    name: "Rotatividade (churn)",
    nameEn: "Churn",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Predição de probabilidade de desistência e identificação de fatores preventivos de risco.",
    summaryEn: "Predicting attrition probability and identifying preventive risk factors.",
    relatedProjectIds: ["survival-time-to-event", "segmentation-churn-ltv-roi"]
  },
  {
    id: "ltv",
    name: "Valor de vida do cliente (LTV)",
    nameEn: "Customer Lifetime Value (LTV)",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Cálculo do valor financeiro esperado que um cliente trará durante o seu ciclo de vida.",
    summaryEn: "Customer Lifetime Value. Calculating the expected financial value a client will bring during their lifecycle.",
    relatedProjectIds: ["segmentation-churn-ltv-roi"]
  },
  {
    id: "roi",
    name: "Retorno sobre o investimento (ROI)",
    nameEn: "Return on Investment (ROI)",
    group: "Otimização e inteligência quantitativa",
    groupEn: "Optimization & Quant Intelligence",
    summary: "Análise quantitativa do retorno financeiro esperado para cada cenário de alocação de orçamento.",
    summaryEn: "Quantitative analysis of expected financial return for each budget allocation scenario.",
    relatedProjectIds: ["segmentation-churn-ltv-roi"]
  },

  // NLP e automação
  {
    id: "sentiment-analysis",
    name: "Análise de sentimentos",
    nameEn: "Sentiment Analysis",
    group: "PLN e automação",
    groupEn: "NLP & Automation",
    summary: "Conversão de texto livre em classificações de sentimento positivas, negativas ou neutras.",
    summaryEn: "Conversion of free text into positive, negative, or neutral sentiment classifications.",
    relatedProjectIds: ["nlp-text-intelligence"]
  },
  {
    id: "topic-modeling",
    name: "Modelagem de tópicos",
    nameEn: "Topic Modeling",
    group: "PLN e automação",
    groupEn: "NLP & Automation",
    summary: "Algoritmos que varrem conjuntos de texto para extrair agrupamentos de temas estruturados.",
    summaryEn: "Algorithms that scan text bodies to extract structured theme groupings.",
    relatedProjectIds: ["nlp-text-intelligence"]
  },
  {
    id: "entity-extraction",
    name: "Extração de entidades",
    nameEn: "Entity Extraction",
    group: "PLN e automação",
    groupEn: "NLP & Automation",
    summary: "Reconhecimento automático de nomes, locais, produtos ou datas importantes em texto livre.",
    summaryEn: "Automatic recognition of names, locations, products, or key dates in free text.",
    relatedProjectIds: ["nlp-text-intelligence"]
  },
  {
    id: "rag",
    name: "Geração aumentada por recuperação (RAG)",
    nameEn: "Retrieval-Augmented Generation (RAG)",
    group: "PLN e automação",
    groupEn: "NLP & Automation",
    summary: "Ligação de bases de dados locais a modelos de inteligência artificial generativa.",
    summaryEn: "Retrieval-Augmented Generation. Connecting local databases to generative AI models.",
    relatedProjectIds: ["rag-knowledge-base"]
  },
  {
    id: "vector-search",
    name: "Pesquisa vetorial",
    nameEn: "Vector Search",
    group: "PLN e automação",
    groupEn: "NLP & Automation",
    summary: "Busca por proximidade semântica utilizando representações matemáticas de texto (embeddings).",
    summaryEn: "Search by semantic proximity using mathematical text representations (embeddings).",
    relatedProjectIds: ["rag-knowledge-base"]
  }
];
